### PR TITLE
chore(github-action): Refine GitHub Actions criteria for builds, pull requests and release

### PR DESCRIPTION
**Pull request by niladrih**
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>

The build.yml and pull_request.yml workflows will ignore pushes made to `docs/`, `changelogs/` and `deploy/helm/` directories, all `.md` files, BUILDMETA, LICENSE, MAINTAINERS and VERSION files.

Added criteria to ignore build workflows on release. 

Added a commit to correct a minor typo in the docs/quickstart.md file.
Ref: #46

### CODE REVIEW

**Comment by niladrih** [comment]
Related PRs:
https://github.com/openebs/node-disk-manager/pull/562
https://github.com/openebs/cstor-operators/pull/272
https://github.com/openebs/zfs-localpv/pull/306
https://github.com/openebs/lvm-localpv/pull/42
https://github.com/openebs/jiva-operator/pull/66
https://github.com/openebs/maya/pull/1797
https://github.com/openebs/cstor-csi/pull/151
https://github.com/openebs/jiva/pull/350
https://github.com/openebs/libcstor/pull/85
https://github.com/openebs/velero-plugin/pull/151
https://github.com/openebs/m-exporter/pull/14
https://github.com/openebs/upgrade/pull/104
https://github.com/openebs/istgt/pull/353

**Review by akhilerm — APPROVED** [review]
LGTM

**Comment by akhilerm** [comment]
@shubham14bajpai @prateekpandey14  PTAL.

**Review by shubham14bajpai — APPROVED** [review]
LGTM

**Pull request merged**
