### PR TITLE
fix(build): update base image tag to alpine:3.12

### PR DESCRIPTION
**Pull request by RolandMa1986**
Signed-off-by: Roland.Ma <rolandma@yunify.com>

## Pull Request template
**Why is this PR required? What issue does it fix?**:
Some vulnerabilities reported by **trivy** when scanning `openebs/provisioner-localpv:2.10.0`, which was base on alpine 3.12.0.

**What this PR does?**:
In this PR I have changed the tag to a more general format as "3.12", so the base image will be up to date to avoid vulnerabilities issues.

**Does this PR require any upgrade changes?**:
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated? 
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track: 
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them: 

**PLEASE REMOVE BELOW INFORMATION BEFORE SUBMITTING**

The PR title message must follow convention:
   `<type>(<scope>): <subject>`.

Where:
    Most common types are:
    * `feat`        - for new features, not a new feature for build script
    * `fix`         - for bug fixes or improvements, not a fix for build script
    * `chore`       - changes not related to production code
    * `docs`        - changes related to documentation
    * `style`       - formatting, missing semi colons, linting fix etc; no significant production code changes
    * `test`        - adding missing tests, refactoring tests; no production code change
    * `refactor`    - refactoring production code, eg. renaming a variable or function name, there should not be any significant production code changes
    * `cherry-pick` - if PR is merged in master branch and raised to release branch(like v0.4.x)
    
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by akhilerm — COMMENTED** [review]
@RolandMa1986 [This](https://github.com/openebs/linux-utils/blob/91d9e86b289d4852599c2ba9d16a2cbf709ac790/Dockerfile#L1) is the version of alpine that we use in linux-utils image, So `3.12` will always point to the latest dot release `3.12.x` right?

**Comment by RolandMa1986** [comment]
@akhilerm, Correct. `3.12` will always point to the latest 3.12.x release.

**Review by akhilerm — APPROVED** [review]
LGTM. Thanks for the fix @RolandMa1986

**Comment by akhilerm** [comment]
@RolandMa1986 raised a cherry-pick PR to v2.10.x branch

**Comment by akhilerm** [comment]
Have created a new release [v2.10.1](https://github.com/openebs/dynamic-localpv-provisioner/releases/tag/v2.10.1) with this vulnerability fix.

**Pull request merged**
